/*
 * Copyright Mesa3D Contributors
 * SPDX-License-Identifier: MIT
 *
 * Autogenerated file, do not edit
 */

#pragma once

#include "compiler/nir/nir.h"
#include "compiler/nir/nir_builder.h"

#include "util/u_printf.h"

#ifdef __cplusplus
extern "C" {
#endif
nir_def *
usclib_emu_ssbo_atomic_comp_swap(nir_builder *b, nir_def *ssbo_buffer, nir_def *ssbo_offset, nir_def *compare, nir_def *data);

nir_def *
usclib_emu_global_atomic_comp_swap(nir_builder *b, nir_def *addr, nir_def *compare, nir_def *data);

void
usclib_barrier(nir_builder *b, nir_def *num_slots, nir_def *counter_offset);

void
usclib_zero_init_wg_mem(nir_builder *b, nir_def *count);

nir_def *
usclib_tex_state_levels(nir_builder *b, nir_def *tex_state);

nir_def *
usclib_tex_state_samples(nir_builder *b, nir_def *tex_state);

nir_def *
usclib_tex_state_address(nir_builder *b, nir_def *tex_state);

nir_def *
usclib_tex_state_array_max(nir_builder *b, nir_def *tex_state);

nir_def *
usclib_tex_state_size(nir_builder *b, nir_def *tex_state, nir_def *num_comps, nir_def *dim, nir_def *is_array, nir_def *is_image, nir_def *lod);

nir_def *
usclib_tex_state_base_level(nir_builder *b, nir_def *tex_state);

nir_def *
usclib_smp_state_mipfilter(nir_builder *b, nir_def *smp_state);

nir_def *
usclib_tex_lod_dval_post_clamp_resource_to_view_space(nir_builder *b, nir_def *tex_state, nir_def *smp_state, nir_def *lod_dval_post_clamp);

nir_def *
usclib_twiddle2d(nir_builder *b, nir_def *coords, nir_def *size);

nir_def *
usclib_twiddle3d(nir_builder *b, nir_def *coords, nir_def *size);

#ifdef __cplusplus
} /* extern C */
#endif
