/*
 * Copyright © 2026 Imagination Technologies Ltd.
 *
 * SPDX-License-Identifier: MIT
 *
 * Autogenerated file, do not edit.
 */

/**
 * \file pdsc_precomp_programs.c
 *
 * \brief Pre-compiled PDS programs.
 */

#include <stddef.h>
#include <stdint.h>

