/*
 * Copyright © 2026 Imagination Technologies Ltd.
 *
 * SPDX-License-Identifier: MIT
 *
 * Autogenerated file, do not edit.
 */

/**
 * \file pdsc_precomp_programs.h
 *
 * \brief Pre-compiled PDS programs header.
 */

#include <stddef.h>
#include <stdint.h>

#pragma once

static inline unsigned
pdsc_precomp_feature_index(enum pdsc_feature feature_variants,
                           enum pdsc_feature features)
{
   if (!feature_variants)
      return 0;

   unsigned index = 0;
   for (enum pdsc_feature f = 0; f <= feature_variants; ++f) {
      /* Skip feature variants we aren't building for. */
      if ((f & ~feature_variants) != 0)
         continue;

      if (f == features)
         return index;

      ++index;
   }

   UNREACHABLE("Invalid features for provided feature_variants.");
}

